import type { FeatureId } from "@/components/svivva-artifact/feature-defs";

/** Normalized crop rect — origin top-left, values 0–1. */
export type ArtworkCrop = {
  id: string;
  u: number;
  v: number;
  w: number;
  h: number;
};

/** Placement on a cube face (spread on face plane + outward offset). */
export type FaceElement = ArtworkCrop & {
  su: number;
  sv: number;
  offset: number;
  planeW: number;
  planeH: number;
  phase?: number;
  bob?: number;
};

/** Floater in a full-screen feature background. */
export type SceneElement = ArtworkCrop & {
  x: number;
  y: number;
  z: number;
  scale: number;
  parallax?: number;
  phase?: number;
  rotZ?: number;
};

export type ArtworkManifest = {
  src: string;
  accentColor: string;
  faceElements: FaceElement[];
  sceneElements: SceneElement[];
};

export const ARTWORK_MANIFESTS: Record<FeatureId, ArtworkManifest> = {
  play: {
    src: "/artworks/play.png",
    accentColor: "#7c5cbf",
    faceElements: [
      {
        id: "note-a",
        u: 0.58,
        v: 0.06,
        w: 0.2,
        h: 0.22,
        su: 0.35,
        sv: 0.35,
        offset: 0.18,
        planeW: 0.42,
        planeH: 0.48,
        phase: 0,
        bob: 0.05,
      },
      {
        id: "note-b",
        u: 0.68,
        v: 0.32,
        w: 0.18,
        h: 0.2,
        su: 0.45,
        sv: -0.1,
        offset: 0.22,
        planeW: 0.38,
        planeH: 0.44,
        phase: 1.1,
        bob: 0.06,
      },
      {
        id: "note-c",
        u: 0.52,
        v: 0.52,
        w: 0.22,
        h: 0.18,
        su: 0.2,
        sv: -0.35,
        offset: 0.2,
        planeW: 0.4,
        planeH: 0.36,
        phase: 2.2,
        bob: 0.05,
      },
      {
        id: "text-cyan",
        u: 0.03,
        v: 0.1,
        w: 0.36,
        h: 0.2,
        su: -0.55,
        sv: 0.4,
        offset: 0.14,
        planeW: 0.55,
        planeH: 0.32,
        phase: 0.5,
        bob: 0.03,
      },
      {
        id: "text-magenta",
        u: 0.03,
        v: 0.36,
        w: 0.36,
        h: 0.2,
        su: -0.55,
        sv: 0.05,
        offset: 0.16,
        planeW: 0.55,
        planeH: 0.32,
        phase: 1.6,
        bob: 0.03,
      },
      {
        id: "guitarist",
        u: 0.48,
        v: 0.18,
        w: 0.48,
        h: 0.72,
        su: 0.15,
        sv: -0.15,
        offset: 0.28,
        planeW: 0.7,
        planeH: 0.95,
        phase: 0.8,
        bob: 0.04,
      },
    ],
    sceneElements: [
      {
        id: "note-1",
        u: 0.62,
        v: 0.08,
        w: 0.16,
        h: 0.2,
        x: -4,
        y: 2,
        z: -4,
        scale: 1.8,
        parallax: 1.2,
        phase: 0,
      },
      {
        id: "note-2",
        u: 0.7,
        v: 0.4,
        w: 0.14,
        h: 0.18,
        x: 5,
        y: -1,
        z: -5,
        scale: 1.5,
        parallax: 0.9,
        phase: 1.2,
      },
      {
        id: "text-stack",
        u: 0.04,
        v: 0.12,
        w: 0.34,
        h: 0.55,
        x: -6,
        y: 0,
        z: -3.5,
        scale: 2.2,
        parallax: 0.6,
        phase: 0.4,
      },
      {
        id: "guitar",
        u: 0.5,
        v: 0.2,
        w: 0.45,
        h: 0.7,
        x: 3,
        y: -0.5,
        z: -6,
        scale: 2.8,
        parallax: 1.0,
        phase: 0.9,
      },
    ],
  },
  seeds: {
    src: "/artworks/seeds.png",
    accentColor: "#5BA8A0",
    faceElements: [
      {
        id: "gold-panel",
        u: 0.03,
        v: 0.14,
        w: 0.44,
        h: 0.36,
        su: -0.35,
        sv: 0.35,
        offset: 0.16,
        planeW: 0.52,
        planeH: 0.48,
        phase: 0,
        bob: 0.04,
      },
      {
        id: "purple-photo",
        u: 0.54,
        v: 0.14,
        w: 0.42,
        h: 0.36,
        su: 0.35,
        sv: 0.35,
        offset: 0.16,
        planeW: 0.5,
        planeH: 0.48,
        phase: 0.8,
        bob: 0.04,
      },
      {
        id: "grain",
        u: 0.03,
        v: 0.54,
        w: 0.44,
        h: 0.36,
        su: -0.35,
        sv: -0.35,
        offset: 0.18,
        planeW: 0.52,
        planeH: 0.48,
        phase: 1.5,
        bob: 0.05,
      },
      {
        id: "courtyard",
        u: 0.54,
        v: 0.54,
        w: 0.42,
        h: 0.36,
        su: 0.35,
        sv: -0.35,
        offset: 0.18,
        planeW: 0.5,
        planeH: 0.48,
        phase: 2.1,
        bob: 0.05,
      },
      {
        id: "staff",
        u: 0.0,
        v: 0.0,
        w: 1.0,
        h: 0.1,
        su: 0,
        sv: 0.55,
        offset: 0.12,
        planeW: 1.1,
        planeH: 0.14,
        phase: 0.3,
        bob: 0.02,
      },
    ],
    sceneElements: [
      {
        id: "quad-tl",
        u: 0.03,
        v: 0.14,
        w: 0.44,
        h: 0.36,
        x: -5.5,
        y: 2.5,
        z: -4,
        scale: 2.4,
        parallax: 0.7,
        phase: 0,
      },
      {
        id: "quad-tr",
        u: 0.54,
        v: 0.14,
        w: 0.42,
        h: 0.36,
        x: 5,
        y: 2,
        z: -5,
        scale: 2.2,
        parallax: 0.85,
        phase: 0.6,
      },
      {
        id: "quad-bl",
        u: 0.03,
        v: 0.54,
        w: 0.44,
        h: 0.36,
        x: -4.5,
        y: -2.5,
        z: -3.5,
        scale: 2.0,
        parallax: 1.0,
        phase: 1.1,
      },
      {
        id: "quad-br",
        u: 0.54,
        v: 0.54,
        w: 0.42,
        h: 0.36,
        x: 5.5,
        y: -2,
        z: -4.5,
        scale: 2.1,
        parallax: 0.9,
        phase: 1.8,
      },
    ],
  },
  orbit: {
    src: "/artworks/orbit.png",
    accentColor: "#3d8a82",
    faceElements: [
      {
        id: "star-a",
        u: 0.04,
        v: 0.52,
        w: 0.14,
        h: 0.2,
        su: -0.4,
        sv: -0.2,
        offset: 0.2,
        planeW: 0.32,
        planeH: 0.4,
        phase: 0,
        bob: 0.06,
      },
      {
        id: "star-b",
        u: 0.8,
        v: 0.58,
        w: 0.14,
        h: 0.18,
        su: 0.42,
        sv: -0.25,
        offset: 0.22,
        planeW: 0.3,
        planeH: 0.36,
        phase: 1.0,
        bob: 0.05,
      },
      {
        id: "star-c",
        u: 0.7,
        v: 0.06,
        w: 0.16,
        h: 0.2,
        su: 0.3,
        sv: 0.4,
        offset: 0.18,
        planeW: 0.34,
        planeH: 0.38,
        phase: 2.0,
        bob: 0.05,
      },
      {
        id: "glitch-face",
        u: 0.28,
        v: 0.12,
        w: 0.44,
        h: 0.42,
        su: 0,
        sv: 0.1,
        offset: 0.25,
        planeW: 0.65,
        planeH: 0.62,
        phase: 0.5,
        bob: 0.03,
      },
      {
        id: "blue-rose",
        u: 0.02,
        v: 0.18,
        w: 0.22,
        h: 0.28,
        su: -0.45,
        sv: 0.15,
        offset: 0.2,
        planeW: 0.38,
        planeH: 0.45,
        phase: 1.5,
        bob: 0.04,
      },
    ],
    sceneElements: [
      {
        id: "star-1",
        u: 0.05,
        v: 0.55,
        w: 0.12,
        h: 0.18,
        x: -6,
        y: -1,
        z: -4,
        scale: 2.0,
        parallax: 1.1,
        phase: 0,
        rotZ: 0.2,
      },
      {
        id: "star-2",
        u: 0.82,
        v: 0.6,
        w: 0.12,
        h: 0.16,
        x: 6.5,
        y: -2,
        z: -5,
        scale: 1.7,
        parallax: 0.95,
        phase: 1.3,
        rotZ: -0.15,
      },
      {
        id: "face",
        u: 0.28,
        v: 0.12,
        w: 0.44,
        h: 0.42,
        x: 0,
        y: 1,
        z: -6,
        scale: 3.2,
        parallax: 0.5,
        phase: 0.7,
      },
      {
        id: "rose",
        u: 0.02,
        v: 0.18,
        w: 0.22,
        h: 0.28,
        x: -7,
        y: 2,
        z: -3.5,
        scale: 2.4,
        parallax: 0.8,
        phase: 1.9,
      },
      {
        id: "moss",
        u: 0.22,
        v: 0.55,
        w: 0.56,
        h: 0.35,
        x: 2,
        y: -3,
        z: -4.5,
        scale: 3.0,
        parallax: 0.6,
        phase: 0.4,
      },
    ],
  },
  security: {
    src: "/artworks/security.png",
    accentColor: "#6B2C4A",
    faceElements: [
      {
        id: "sphere-top",
        u: 0.38,
        v: 0.1,
        w: 0.24,
        h: 0.24,
        su: 0,
        sv: 0.35,
        offset: 0.22,
        planeW: 0.36,
        planeH: 0.36,
        phase: 0,
        bob: 0.05,
      },
      {
        id: "sphere-bot",
        u: 0.38,
        v: 0.34,
        w: 0.24,
        h: 0.24,
        su: 0,
        sv: 0.05,
        offset: 0.24,
        planeW: 0.36,
        planeH: 0.36,
        phase: 1.2,
        bob: 0.05,
      },
      {
        id: "filigree",
        u: 0.18,
        v: 0.6,
        w: 0.64,
        h: 0.32,
        su: 0,
        sv: -0.35,
        offset: 0.18,
        planeW: 0.85,
        planeH: 0.45,
        phase: 0.6,
        bob: 0.03,
      },
      {
        id: "heart-text",
        u: 0.05,
        v: 0.05,
        w: 0.35,
        h: 0.2,
        su: -0.4,
        sv: 0.4,
        offset: 0.14,
        planeW: 0.5,
        planeH: 0.3,
        phase: 2.0,
        bob: 0.04,
      },
    ],
    sceneElements: [
      {
        id: "crystal-top",
        u: 0.38,
        v: 0.1,
        w: 0.24,
        h: 0.24,
        x: -1,
        y: 3,
        z: -5,
        scale: 2.2,
        parallax: 0.8,
        phase: 0,
      },
      {
        id: "crystal-bot",
        u: 0.38,
        v: 0.34,
        w: 0.24,
        h: 0.24,
        x: 2,
        y: 0.5,
        z: -4,
        scale: 2.0,
        parallax: 1.0,
        phase: 1.1,
      },
      {
        id: "frame",
        u: 0.18,
        v: 0.6,
        w: 0.64,
        h: 0.32,
        x: 0,
        y: -2.5,
        z: -6,
        scale: 3.5,
        parallax: 0.5,
        phase: 0.5,
      },
      {
        id: "heart",
        u: 0.05,
        v: 0.05,
        w: 0.35,
        h: 0.2,
        x: -6,
        y: 3.5,
        z: -3.5,
        scale: 2.0,
        parallax: 0.9,
        phase: 1.7,
      },
    ],
  },
  api: {
    src: "/artworks/api.png",
    accentColor: "#9b4d6e",
    faceElements: [
      {
        id: "flower-br",
        u: 0.55,
        v: 0.52,
        w: 0.4,
        h: 0.42,
        su: 0.35,
        sv: -0.3,
        offset: 0.2,
        planeW: 0.55,
        planeH: 0.58,
        phase: 0,
        bob: 0.05,
      },
      {
        id: "flower-tl",
        u: 0.02,
        v: 0.06,
        w: 0.34,
        h: 0.34,
        su: -0.38,
        sv: 0.38,
        offset: 0.18,
        planeW: 0.48,
        planeH: 0.5,
        phase: 1.0,
        bob: 0.04,
      },
      {
        id: "paper-hang",
        u: 0.32,
        v: 0.22,
        w: 0.36,
        h: 0.26,
        su: 0,
        sv: 0.05,
        offset: 0.22,
        planeW: 0.5,
        planeH: 0.38,
        phase: 0.5,
        bob: 0.04,
      },
      {
        id: "fold-panel",
        u: 0.55,
        v: 0.02,
        w: 0.4,
        h: 0.32,
        su: 0.3,
        sv: 0.42,
        offset: 0.16,
        planeW: 0.52,
        planeH: 0.45,
        phase: 1.8,
        bob: 0.03,
      },
    ],
    sceneElements: [
      {
        id: "flower-1",
        u: 0.55,
        v: 0.52,
        w: 0.38,
        h: 0.4,
        x: 5,
        y: -2.5,
        z: -5,
        scale: 2.6,
        parallax: 0.9,
        phase: 0,
        rotZ: 0.1,
      },
      {
        id: "flower-2",
        u: 0.02,
        v: 0.06,
        w: 0.32,
        h: 0.32,
        x: -5.5,
        y: 2.5,
        z: -4,
        scale: 2.2,
        parallax: 1.0,
        phase: 1.2,
        rotZ: -0.08,
      },
      {
        id: "paper",
        u: 0.32,
        v: 0.22,
        w: 0.36,
        h: 0.26,
        x: 0,
        y: 0,
        z: -6,
        scale: 2.8,
        parallax: 0.6,
        phase: 0.6,
      },
      {
        id: "fold",
        u: 0.55,
        v: 0.02,
        w: 0.4,
        h: 0.32,
        x: 4,
        y: 3,
        z: -3.5,
        scale: 2.4,
        parallax: 0.75,
        phase: 1.5,
      },
    ],
  },
  hardware: {
    src: "/artworks/hardware.png",
    accentColor: "#b5547a",
    faceElements: [
      {
        id: "cube-main",
        u: 0.56,
        v: 0.5,
        w: 0.38,
        h: 0.42,
        su: 0.35,
        sv: -0.3,
        offset: 0.28,
        planeW: 0.58,
        planeH: 0.62,
        phase: 0,
        bob: 0.05,
      },
      {
        id: "cube-green",
        u: 0.66,
        v: 0.02,
        w: 0.28,
        h: 0.3,
        su: 0.35,
        sv: 0.38,
        offset: 0.2,
        planeW: 0.42,
        planeH: 0.45,
        phase: 1.0,
        bob: 0.04,
      },
      {
        id: "cube-red",
        u: 0.02,
        v: 0.32,
        w: 0.28,
        h: 0.32,
        su: -0.38,
        sv: 0.05,
        offset: 0.22,
        planeW: 0.44,
        planeH: 0.48,
        phase: 0.6,
        bob: 0.05,
      },
      {
        id: "vintage",
        u: 0.02,
        v: 0.6,
        w: 0.3,
        h: 0.35,
        su: -0.35,
        sv: -0.35,
        offset: 0.18,
        planeW: 0.48,
        planeH: 0.52,
        phase: 1.8,
        bob: 0.04,
      },
      {
        id: "swimmers",
        u: 0.56,
        v: 0.26,
        w: 0.36,
        h: 0.22,
        su: 0.2,
        sv: 0.15,
        offset: 0.2,
        planeW: 0.55,
        planeH: 0.34,
        phase: 2.2,
        bob: 0.03,
      },
    ],
    sceneElements: [
      {
        id: "hand-cube",
        u: 0.56,
        v: 0.5,
        w: 0.38,
        h: 0.42,
        x: 4.5,
        y: -2,
        z: -5.5,
        scale: 3.0,
        parallax: 0.85,
        phase: 0,
      },
      {
        id: "green-cube",
        u: 0.66,
        v: 0.02,
        w: 0.28,
        h: 0.3,
        x: 6,
        y: 3,
        z: -4,
        scale: 2.0,
        parallax: 1.1,
        phase: 1.0,
      },
      {
        id: "red-cube",
        u: 0.02,
        v: 0.32,
        w: 0.28,
        h: 0.32,
        x: -6,
        y: 1,
        z: -4.5,
        scale: 2.1,
        parallax: 0.95,
        phase: 0.5,
      },
      {
        id: "figures",
        u: 0.02,
        v: 0.6,
        w: 0.3,
        h: 0.35,
        x: -5,
        y: -3,
        z: -3.5,
        scale: 2.4,
        parallax: 0.7,
        phase: 1.6,
      },
      {
        id: "swim",
        u: 0.56,
        v: 0.26,
        w: 0.36,
        h: 0.22,
        x: 3,
        y: 2.5,
        z: -6,
        scale: 2.6,
        parallax: 0.6,
        phase: 2.1,
      },
    ],
  },
};

export function getManifest(id: FeatureId): ArtworkManifest {
  return ARTWORK_MANIFESTS[id];
}
