import archiver from "archiver";
import { PassThrough } from "stream";
import { finished } from "stream/promises";
import type { FeatureId } from "@/components/svivva-artifact/feature-defs";
import {
  CUBE_GEOMETRY_FACE_ORDER,
  buildMasterProductJourney,
  listCubeFaces,
  type MasterProductJourney,
} from "./cube-faces";
import { isCubeJourneyComplete } from "./cube-face-progress";
import {
  DEFAULT_MASTER_PRODUCT_JOURNEY,
  exportWalkthroughJson,
  exportWalkthroughMarkdown,
} from "./master-product-walkthrough";

export { DEFAULT_MASTER_PRODUCT_JOURNEY };

export type WalkthroughPackFile = {
  path: string;
  content: string;
};

export type WalkthroughPack = {
  slug: string;
  productName: string;
  files: WalkthroughPackFile[];
};

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "product"
  );
}

function padStep(n: number): string {
  return String(n).padStart(2, "0");
}

function exportChecklistCsv(
  journey: MasterProductJourney,
  visitedFaceIds?: ReadonlySet<FeatureId>,
): string {
  const header = "step,face_id,face_label,name,href,platform_mode,action,done";
  const rows = journey.steps.map((s) =>
    [
      s.step,
      s.faceId,
      s.shortLabel,
      `"${s.name.replace(/"/g, '""')}"`,
      s.href,
      s.platformMode ?? "",
      `"${s.action.replace(/"/g, '""')}"`,
      visitedFaceIds?.has(s.faceId) ? "yes" : "",
    ].join(","),
  );
  return [header, ...rows].join("\n");
}

function stepMarkdown(
  step: MasterProductJourney["steps"][number],
  journey: MasterProductJourney,
): string {
  return `# Step ${step.step}: ${step.shortLabel} — ${step.name}

**Product:** ${journey.productName}

## Route
${step.href}

## Role
${step.role}

## Action
${step.action}

${step.platformMode ? `## Platform mode\n${step.platformMode === "physical" ? "Crest (physical)" : "Signal (digital)"}\n` : ""}
## Checklist
- [ ] Open ${step.shortLabel}
- [ ] Complete the action above for “${journey.productName}”
- [ ] Mark done in \`checklist.csv\`
`;
}

function packReadme(journey: MasterProductJourney, slug: string): string {
  return `# ${journey.productName} — ZZAI cube walkthrough pack

${journey.productBrief}

**Master bus out:** ${journey.masterBusOut}

This ZIP contains ${journey.steps.length} step files — one per cube face — plus JSON, markdown, and CSV checklists you can use offline or share with a team.

## Files

| File | Purpose |
|------|---------|
| \`journey.json\` | Full structured journey |
| \`walkthrough.md\` | Printable six-face guide |
| \`checklist.csv\` | Track progress (open in Sheets/Excel) |
| \`routes.json\` | All face URLs in order |
| \`cube-geometry.json\` | 3D cube face index mapping |
| \`steps/*.md\` | One file per cube face |

## Suggested order

${journey.steps.map((s) => `${s.step}. **${s.shortLabel}** — ${s.href}`).join("\n")}

Generated by ZZAI (\`${slug}-cube-walkthrough-pack\`).
`;
}

export type WalkthroughPackOptions = {
  /** Faces the user opened on the homepage cube before downloading. */
  visitedFaceIds?: readonly FeatureId[];
};

/** Build every file in the downloadable pack (no zip yet). */
export function buildWalkthroughPack(
  journey: MasterProductJourney = DEFAULT_MASTER_PRODUCT_JOURNEY,
  options: WalkthroughPackOptions = {},
): WalkthroughPack {
  const slug = slugify(journey.productName);
  const visitedSet = options.visitedFaceIds?.length ? new Set(options.visitedFaceIds) : undefined;
  const journeyComplete = visitedSet ? isCubeJourneyComplete(visitedSet) : false;
  const files: WalkthroughPackFile[] = [
    {
      path: "README.md",
      content: packReadme(journey, slug),
    },
    {
      path: "manifest.json",
      content: JSON.stringify(
        {
          productName: journey.productName,
          productBrief: journey.productBrief,
          masterBusOut: journey.masterBusOut,
          stepCount: journey.steps.length,
          generatedAt: new Date().toISOString(),
          cubeProgress: visitedSet
            ? {
                visitedFaceIds: [...visitedSet],
                journeyComplete,
              }
            : undefined,
          files: [
            "README.md",
            "manifest.json",
            "journey.json",
            "walkthrough.md",
            "checklist.csv",
            "routes.json",
            "cube-geometry.json",
            ...journey.steps.map((s) => `steps/${padStep(s.step)}-${s.faceId}.md`),
          ],
        },
        null,
        2,
      ),
    },
    { path: "journey.json", content: exportWalkthroughJson(journey) },
    { path: "walkthrough.md", content: exportWalkthroughMarkdown(journey) },
    { path: "checklist.csv", content: exportChecklistCsv(journey, visitedSet) },
    {
      path: "routes.json",
      content: JSON.stringify(
        journey.steps.map((s) => ({
          step: s.step,
          faceId: s.faceId,
          shortLabel: s.shortLabel,
          href: s.href,
        })),
        null,
        2,
      ),
    },
    {
      path: "cube-geometry.json",
      content: JSON.stringify(
        {
          geometryFaceOrder: CUBE_GEOMETRY_FACE_ORDER,
          faces: listCubeFaces().map((f) => ({
            id: f.id,
            geometryIndex: f.geometryIndex,
            shortLabel: f.shortLabel,
            href: f.href,
          })),
        },
        null,
        2,
      ),
    },
  ];

  for (const step of journey.steps) {
    files.push({
      path: `steps/${padStep(step.step)}-${step.faceId}.md`,
      content: stepMarkdown(step, journey),
    });
  }

  return { slug, productName: journey.productName, files };
}

export function walkthroughPackZipFilename(pack: WalkthroughPack): string {
  return `${pack.slug}-cube-walkthrough-pack.zip`;
}

/** Zip the pack for download (server or scripts). */
export async function buildWalkthroughPackZipBuffer(
  journey: MasterProductJourney = DEFAULT_MASTER_PRODUCT_JOURNEY,
  options: WalkthroughPackOptions = {},
): Promise<{ buffer: Buffer; filename: string; pack: WalkthroughPack }> {
  const pack = buildWalkthroughPack(journey, options);
  const archive = archiver("zip", { zlib: { level: 9 } });
  const passthrough = new PassThrough();
  const chunks: Buffer[] = [];
  passthrough.on("data", (chunk: Buffer) => chunks.push(chunk));
  archive.pipe(passthrough);

  for (const file of pack.files) {
    archive.append(file.content, { name: file.path });
  }

  archive.on("error", (err) => passthrough.destroy(err));
  await archive.finalize();
  await finished(passthrough);

  const buffer = Buffer.concat(chunks);
  if (buffer.length < 22) throw new Error("Walkthrough pack zip is empty");

  return { buffer, filename: walkthroughPackZipFilename(pack), pack };
}

export function buildWalkthroughPackFromInput(
  input: {
    productName?: string;
    productBrief?: string;
  },
  options: WalkthroughPackOptions = {},
): WalkthroughPack {
  const name = input.productName?.trim() || DEFAULT_MASTER_PRODUCT_JOURNEY.productName;
  const journey = buildMasterProductJourney({
    productName: name,
    productBrief: input.productBrief,
  });
  return buildWalkthroughPack(journey, options);
}
