import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth/session";
import { projectRepository } from "@/lib/repositories";
import { db } from "@/lib/db";
import { sdkExports } from "@/lib/schema";
import { nanoid } from "nanoid";
import crypto from "crypto";

interface RouteParams {
  params: Promise<{ id: string }>;
}

function generatePythonSDK(project: {
  id: string;
  name: string;
  slug: string;
  systemPrompt: string;
  outputSchema: unknown;
}, baseUrl: string): string {
  return `"""
${project.name} - Python SDK
Generated by Svivva API Platform
"""

import requests
from typing import Any, Dict, Optional

class ${toPascalCase(project.slug)}Client:
    """Client for ${project.name} API"""
    
    def __init__(self, api_key: str, base_url: str = "${baseUrl}"):
        self.api_key = api_key
        self.base_url = base_url
        self.endpoint = f"{base_url}/api/runtime/${project.id}/main"
    
    def execute(self, input_data: Any, timeout: int = 30) -> Dict[str, Any]:
        """
        Execute the ${project.name} API
        
        Args:
            input_data: The input to process (string or dict)
            timeout: Request timeout in seconds
            
        Returns:
            API response with success, data, and metadata
        """
        headers = {
            "Content-Type": "application/json",
            "X-API-Key": self.api_key
        }
        
        payload = {"input": input_data}
        
        response = requests.post(
            self.endpoint,
            json=payload,
            headers=headers,
            timeout=timeout
        )
        response.raise_for_status()
        
        return response.json()
    
    def get_info(self) -> Dict[str, Any]:
        """Get API endpoint information"""
        response = requests.get(self.endpoint)
        response.raise_for_status()
        return response.json()


# Quick usage example
if __name__ == "__main__":
    # Initialize the client
    client = ${toPascalCase(project.slug)}Client(
        api_key="your-api-key-here"
    )
    
    # Execute the API
    result = client.execute("Your input here")
    print(result)
`;
}

function generateNodeSDK(project: {
  id: string;
  name: string;
  slug: string;
  systemPrompt: string;
  outputSchema: unknown;
}, baseUrl: string): string {
  return `/**
 * ${project.name} - Node.js SDK
 * Generated by Svivva API Platform
 */

interface ExecuteResponse {
  success: boolean;
  data: any;
  processingTime?: number;
  version?: string;
}

interface APIInfo {
  projectId: string;
  endpoint: string;
  name: string;
  description?: string;
  outputSchema: object;
}

class ${toPascalCase(project.slug)}Client {
  private apiKey: string;
  private baseUrl: string;
  private endpoint: string;

  constructor(apiKey: string, baseUrl: string = "${baseUrl}") {
    this.apiKey = apiKey;
    this.baseUrl = baseUrl;
    this.endpoint = \`\${baseUrl}/api/runtime/${project.id}/main\`;
  }

  /**
   * Execute the ${project.name} API
   * @param input - The input to process (string or object)
   * @returns API response with success, data, and metadata
   */
  async execute(input: string | object): Promise<ExecuteResponse> {
    const response = await fetch(this.endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": this.apiKey,
      },
      body: JSON.stringify({ input }),
    });

    if (!response.ok) {
      throw new Error(\`API error: \${response.status} \${response.statusText}\`);
    }

    return response.json();
  }

  /**
   * Get API endpoint information
   */
  async getInfo(): Promise<APIInfo> {
    const response = await fetch(this.endpoint);
    if (!response.ok) {
      throw new Error(\`API error: \${response.status} \${response.statusText}\`);
    }
    return response.json();
  }
}

// Export for ES modules
export { ${toPascalCase(project.slug)}Client };

// Quick usage example
async function main() {
  const client = new ${toPascalCase(project.slug)}Client(
    "your-api-key-here"
  );
  
  const result = await client.execute("Your input here");
  console.log(result);
}

// Run example if this is the main module
// main().catch(console.error);
`;
}

function generateCurlExample(project: {
  id: string;
  name: string;
}, baseUrl: string): string {
  return `# ${project.name} - cURL Examples
# Generated by Svivva API Platform

# Execute the API
curl -X POST "${baseUrl}/api/runtime/${project.id}/main" \\
  -H "Content-Type: application/json" \\
  -H "X-API-Key: your-api-key-here" \\
  -d '{"input": "Your input here"}'

# Get API information
curl "${baseUrl}/api/runtime/${project.id}/main"
`;
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;
    const project = await projectRepository.findById(id);

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    if (project.ownerId !== user.id) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const baseUrl = request.nextUrl.origin;
    const language = request.nextUrl.searchParams.get("language") || "all";
    const download = request.nextUrl.searchParams.get("download") === "true";

    const projectData = {
      id: project.id,
      name: project.name,
      slug: project.slug,
      systemPrompt: project.systemPrompt,
      outputSchema: project.outputSchema,
    };

    if (language === "python") {
      const code = generatePythonSDK(projectData, baseUrl);
      if (download) {
        return new NextResponse(code, {
          headers: {
            "Content-Type": "text/x-python",
            "Content-Disposition": `attachment; filename="${project.slug}_client.py"`,
          },
        });
      }
      return NextResponse.json({ language: "python", code });
    }

    if (language === "node" || language === "typescript") {
      const code = generateNodeSDK(projectData, baseUrl);
      if (download) {
        return new NextResponse(code, {
          headers: {
            "Content-Type": "text/typescript",
            "Content-Disposition": `attachment; filename="${project.slug}_client.ts"`,
          },
        });
      }
      return NextResponse.json({ language: "typescript", code });
    }

    if (language === "curl") {
      const code = generateCurlExample(projectData, baseUrl);
      if (download) {
        return new NextResponse(code, {
          headers: {
            "Content-Type": "text/plain",
            "Content-Disposition": `attachment; filename="${project.slug}_examples.sh"`,
          },
        });
      }
      return NextResponse.json({ language: "curl", code });
    }

    const specHash = crypto
      .createHash("md5")
      .update(JSON.stringify(project.outputSchema))
      .digest("hex");

    return NextResponse.json({
      project: {
        id: project.id,
        name: project.name,
        slug: project.slug,
      },
      specHash,
      sdks: {
        python: generatePythonSDK(projectData, baseUrl),
        typescript: generateNodeSDK(projectData, baseUrl),
        curl: generateCurlExample(projectData, baseUrl),
      },
    });
  } catch (error) {
    console.error("Error generating SDK:", error);
    return NextResponse.json({ error: "Failed to generate SDK" }, { status: 500 });
  }
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;
    const project = await projectRepository.findById(id);

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    if (project.ownerId !== user.id) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await request.json();
    const { language } = body as { language: string };

    if (!["python", "typescript", "curl"].includes(language)) {
      return NextResponse.json({ error: "Invalid language" }, { status: 400 });
    }

    const specHash = crypto
      .createHash("md5")
      .update(JSON.stringify(project.outputSchema))
      .digest("hex");

    const [exportRecord] = await db
      .insert(sdkExports)
      .values({
        id: nanoid(),
        projectId: id,
        language,
        version: "1.0.0",
        specHash,
      })
      .returning();

    return NextResponse.json({
      success: true,
      export: exportRecord,
    });
  } catch (error) {
    console.error("Error recording SDK export:", error);
    return NextResponse.json({ error: "Failed to record export" }, { status: 500 });
  }
}
